"""Generate the weapon and prop models.

    python tools/models/build.py

Writes:
    assets/weapons/<Name>.glb, assets/props/<Name>.glb   ready for Studio's Import 3D
    assets/weapons/preview.png, assets/props/preview.png two views of every model
    src/tools/Palette.luau                               colours for the Studio fit step

Each GLB holds one mesh per palette key plus tiny marker meshes. The fit step
(src/tools/Fit.luau) reads the markers to find the origin, the forward, up and
right directions and the scale, then deletes them. Weapons also carry a muzzle
marker.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from meshkit import merge, octahedron, write_glb  # noqa: E402
from palette import PALETTE  # noqa: E402
from props import PROPS  # noqa: E402
from render import contact_sheet  # noqa: E402
from weapons import WEAPONS  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
PALETTE_FILE = ROOT / "src" / "tools" / "Palette.luau"

MARKER_RADIUS = 0.02
MARKER_PALETTE = {"Marker": {"color": (255, 0, 255)}}
FRAME = {"MarkOrigin": (0, 0, 0), "MarkForward": (0, 0, -1), "MarkUp": (0, 1, 0), "MarkRight": (1, 0, 0)}


def markers(points):
    return [(name, "Marker", octahedron(point, MARKER_RADIUS)) for name, point in points.items()]


def by_key(parts):
    groups = {}
    for key, piece in parts:
        groups.setdefault(key, []).append(piece)
    return [(key, key, merge(pieces)) for key, pieces in groups.items()]


def write_kit(folder, models, views):
    """`models` is a list of (name, parts, extra marker points)."""
    folder.mkdir(parents=True, exist_ok=True)
    rows = []
    for name, parts, extra in models:
        meshes = by_key(parts)
        write_glb(folder / f"{name}.glb", meshes + markers({**FRAME, **extra}), {**PALETTE, **MARKER_PALETTE})

        triangles = sum(len(piece[0]) for _, _, piece in meshes)
        points = merge([piece for _, _, piece in meshes])[0].reshape(-1, 3)
        size = points.max(axis=0) - points.min(axis=0)
        label = f"{name}  -  {triangles} triangles, {size[0]:.1f} x {size[1]:.1f} x {size[2]:.1f} studs"
        print(f"{folder.name:8} {name:11} {len(meshes)} meshes  {triangles:5} triangles")
        rows.append((label, [(key, piece) for _, key, piece in meshes]))
    contact_sheet(folder / "preview.png", rows, PALETTE, views)


def write_palette():
    lines = [
        "-- Generated by tools/models/build.py from tools/models/palette.py. Do not edit.",
        "-- MeshPart name -> colour and material applied by the fit step.",
        "",
        "return {",
    ]
    for key, entry in PALETTE.items():
        r, g, b = entry["color"]
        lines.append(f'\t{key} = {{ color = {{ {r}, {g}, {b} }}, material = "{entry["material"]}" }},')
    lines += ["}", ""]
    PALETTE_FILE.parent.mkdir(parents=True, exist_ok=True)
    PALETTE_FILE.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main():
    weapons = []
    for name, design in WEAPONS.items():
        parts, muzzle = design()
        weapons.append((name, parts, {"MarkMuzzle": muzzle}))
    write_kit(ROOT / "assets" / "weapons", weapons, views=((0, 0), (38, 18)))

    props = [(name, builder(), {}) for name, (builder, _) in PROPS.items()]
    write_kit(ROOT / "assets" / "props", props, views=((28, 18), (68, 26)))

    write_palette()


if __name__ == "__main__":
    main()
