"""Build the high-detail weapons in Blender.

    pip install bpy numpy pillow      (bpy needs the Python version Blender ships for)
    python tools/models/hd/build.py               every weapon
    python tools/models/hd/build.py AK47 MP5      just these
    python tools/models/hd/build.py --fast AK47   quicker, noisier previews

Writes assets/weapons_hd/<Name>.glb, <Name>.png (studio renders) and
<Name>.json (parts, finishes, animation groups, muzzle position in studs).
"""

import importlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from kit import Gun  # noqa: E402
from preview import render  # noqa: E402

ROOT = HERE.parents[2]
OUT = ROOT / "assets" / "weapons_hd"
LUAU = ROOT / "src" / "tools" / "HdWeapons.luau"

# What the Studio fit step applies to each finish: sRGB colour and Roblox material.
FINISHES = {
    "Steel": ((44, 46, 51), "Metal"),
    "Bare": ((150, 153, 158), "Metal"),
    "Wood": ((112, 50, 24), "Wood"),
    "Polymer": ((30, 30, 32), "SmoothPlastic"),
}


def write_luau():
    lines = [
        "-- Generated by tools/models/hd/build.py from assets/weapons_hd/*.json. Do not edit.",
        "-- Finish of each part of the detailed weapons, and the group it moves with.",
        "",
        "return {",
        "\tfinishes = {",
    ]
    for key, ((r, g, b), material) in FINISHES.items():
        lines.append(f'\t\t{key} = {{ color = {{ {r}, {g}, {b} }}, material = "{material}" }},')
    lines += ["\t},", "\tweapons = {"]
    for path in sorted(OUT.glob("*.json")):
        manifest = json.loads(path.read_text(encoding="utf-8"))
        lines.append(f"\t\t{manifest['name']} = {{")
        for part, info in manifest["parts"].items():
            lines.append(f'\t\t\t{part} = {{ finish = "{info["finish"]}", group = "{info["group"]}" }},')
        lines.append("\t\t},")
    lines += ["\t},", "}", ""]
    LUAU.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def designs():
    return {
        module.NAME: module
        for module in (importlib.import_module(f"guns.{path.stem}") for path in sorted((HERE / "guns").glob("*.py")))
        if hasattr(module, "NAME")
    }


def main(args):
    fast = "--fast" in args
    names = [a for a in args if not a.startswith("--")]
    available = designs()
    unknown = [n for n in names if n not in available]
    if unknown:
        sys.exit(f"unknown weapon(s): {', '.join(unknown)}; have {', '.join(available)}")

    OUT.mkdir(parents=True, exist_ok=True)
    for name in names or list(available):
        design = available[name]
        gun = Gun(name)
        grip, muzzle = design.build(gun)
        gun.finish(grip, muzzle, design.STUDS_PER_METRE)
        gun.export(OUT / f"{name}.glb")

        triangles = gun.triangles()
        manifest = {
            "name": name,
            "studsPerMetre": design.STUDS_PER_METRE,
            "muzzle": [round(c, 4) for c in (gun.muzzle.x, gun.muzzle.z, -gun.muzzle.y)],
            "parts": {
                part: {**info, "triangles": triangles[part]} for part, info in gun.parts.items()
            },
        }
        (OUT / f"{name}.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        render(gun, OUT / f"{name}.png", samples=24 if fast else 96)
        print(f"{name}: {sum(triangles.values())} triangles in {len(triangles)} parts, largest "
              f"{max(triangles, key=triangles.get)} {max(triangles.values())}")
    write_luau()


if __name__ == "__main__":
    main(sys.argv[1:])
